<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Author ID' => '',
    'Create Uploaded Files' => '',
    'File ID' => '',
    'Filename' => '',
    'ID' => '',
    'It is recommended you use an upgraded browser to display the {type} control properly.' => '',
    'Preview' => '',
    'Update {modelClass}: ' => '',
    'Uploaded Files' => '',
    'book name' => 'название',
    'Are you sure you want to delete this item?' => 'Точно удалить?',
    'Authors' => 'Авторы',
    'Books' => 'Книги',
    'Create' => 'Создать',
    'Create Authors' => 'создать...',
    'Create Books' => 'создать...',
    'Date' => 'Дата выхода книги',
    'Date Create' => 'Дата добавления',
    'Date Update' => 'Дата обновления',
    'Delete' => 'удалить',
    'Firstname' => 'Имя',
    'Lastname' => 'Фамилия',
    'Name' => 'Название',
    'Published from' => 'с',
    'Published to' => 'по',
    'Reset' => 'Сброс',
    'Search' => 'искать',
    'Size' => 'Размер',
    'Type' => 'Тип',
    'Update' => 'редактировать',
    'authorFirstName' => 'Имя',
    'authorFullName' => 'Автор',
    'authorLastName' => 'Фамилия',
    'book image' => 'Изображение',
    'image' => 'Изображение',
    'thumbnail' => 'Превью',
];
